---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: user_id from the path
      required: true
      schema:
        type: string
    get:
      summary: list all posts of selected user
      responses:
        '200':
          description: successful
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: 127.0.0.1:3000/api
